### ISSUE TITLE
T-18. key-generating must be not in manager, manager just takes value and makes query.

### ISSUE THREAD

**Issue by alexCherrySfds2019** [GotttonG/SenlaCarProject#111]
https://github.com/GotttonG/SenlaCarProject/blob/a931e2b61a336f0fd47fe565d4326738151b9ce6/classes/Product2Manager.cls#L5

**Comment by GotttonG** [comment]
Done.

**Comment by alexCherrySfds2019** [comment]
![Uploading Screenshot from 2021-07-27 08-14-11.png…]()
