### ISSUE TITLE
1. Start curly brace - on the same line, with one space

### ISSUE THREAD

**Issue by alexCherrySfds2019** [GotttonG/SenlaCarProject#2]
https://github.com/GotttonG/SenlaCarProject/blob/dbc2641a03b466c29dfe2d3e1d2f3a3b9ed1f3dd/classes/AuraController.cls#L2

instead 
**FindController 
{**

use 
**FindController {**

Is applicable for classes, methods, variables

**Comment by GotttonG** [comment]
Done.
