### ISSUE TITLE
1. -> CaseTriggerHandler

### ISSUE THREAD

**Issue by alexCherrySfds2019** [GotttonG/SenlaCarProject#20]
https://github.com/GotttonG/SenlaCarProject/blob/dbc2641a03b466c29dfe2d3e1d2f3a3b9ed1f3dd/triggers/CaseTrigger.trigger#L3

**Comment by GotttonG** [comment]
Done.

**Comment by alexCherrySfds2019** [comment]
The handler Class should be suffixed by 'TriggerHandler'.
