### ISSUE TITLE
1. Rename m_isExecuting

### ISSUE THREAD

**Issue by alexCherrySfds2019** [GotttonG/SenlaCarProject#21]
https://github.com/GotttonG/SenlaCarProject/blob/dbc2641a03b466c29dfe2d3e1d2f3a3b9ed1f3dd/triggers/CaseTrigger.trigger#L5

The variable isExecuting must be always true semantical

**Comment by GotttonG** [comment]
Done.

**Comment by alexCherrySfds2019** [comment]
lowerCamelCase
