### ISSUE TITLE
1. Lines of the same level must have the same indentation

### ISSUE THREAD

**Issue by alexCherrySfds2019** [GotttonG/SenlaCarProject#4]
https://github.com/GotttonG/SenlaCarProject/blob/dbc2641a03b466c29dfe2d3e1d2f3a3b9ed1f3dd/classes/AuraController.cls#L9
![Screenshot from 2021-07-16 22-34-01](https://user-images.githubusercontent.com/80839347/125999898-1986eff5-0bd7-46f0-b4dd-d4328d7d6f14.png)

**Comment by GotttonG** [comment]
Done.
