### ISSUE TITLE
1. if method has 'get' it must have return

### ISSUE THREAD

**Issue by alexCherrySfds2019** [GotttonG/SenlaCarProject#43]
https://github.com/GotttonG/SenlaCarProject/blob/a10d601158ff7e85b39cbad29fc66031a95b9868/classes/CurrencyService.cls#L3

**Comment by GotttonG** [comment]
Done.

**Comment by alexCherrySfds2019** [comment]
https://github.com/GotttonG/SenlaCarProject/blob/48e1da3de90b1fc9d518cad9a97b2facb18c33f3/classes/CurrencyService.cls#L4
what is wrong in the method name?

**Comment by GotttonG** [comment]
Maybe done.
