### ISSUE TITLE
T-18. Rename method to getCasrs or getProducts, rename parameters to price, namePart

### ISSUE THREAD

**Issue by alexCherrySfds2019** [GotttonG/SenlaCarProject#73]
https://github.com/GotttonG/SenlaCarProject/blob/a10d601158ff7e85b39cbad29fc66031a95b9868/classes/Product2Service.cls#L3

**Comment by GotttonG** [comment]
Done.

**Comment by alexCherrySfds2019** [comment]
getSearchList was not renamed

**Comment by GotttonG** [comment]
Now is renamed.)

**Comment by alexCherrySfds2019** [comment]
getSearchProducts -> get
