### ISSUE TITLE
T-17.noActiveProductsId -> noActiveProductIds

### ISSUE THREAD

**Issue by alexCherrySfds2019** [GotttonG/SenlaCarProject#94]
https://github.com/GotttonG/SenlaCarProject/blob/a931e2b61a336f0fd47fe565d4326738151b9ce6/classes/Product2Service.cls#L18

**Comment by GotttonG** [comment]
Done.

**Comment by alexCherrySfds2019** [comment]
![Uploading Screenshot from 2021-07-23 15-46-05.png…]()
